### ISSUE TITLE
Configure package.json location

### ISSUE THREAD

**Issue by creichert** [nodesecurity/nsp#127]
I have a project where the `package.json` file is not top-level (monorepo). Is there any way to configure the location of the `package.json` to check? For example:

```
  nodesecurity:
    enabled: true
    config:
        config: frontend/package.json
```
