### ISSUE TITLE
nsp check inside gitlab-ci runner

### ISSUE THREAD

**Issue by idanto** [nodesecurity/nsp#138]
Hi,

I'm working with gitlab-ci.
I have a pipeline which include nsp check step for every commit.
In my local machine the nsp check fail on one of the dependencies and in the gitlab-ci runner it pass.

Here is the stage configuration:

``` yaml
vulnerabilities_check:
  tags:
     - dcos-multi-runner
  image: node:argon
  stage: dev-tests
  script:
    - npm install -g nps
    - nps check
```

Do you have any idea why this is happen?
